version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app

  server:
    image: node:alpine
    volumes:
      - ./server:/usr/local/server
    working_dir: /usr/local/server
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://root:password@db/app
      - JWT_SECRET=secret
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - db

  app:
    image: node:17.0.0-alpine
    user: node
    working_dir: /home/node
    entrypoint: node
    tty: true
    ports:
      - 8000:8000
    stdin_open: true
    volumes:
      - ./app:/home/node

  adminer:
    image: adminer
    ports:
      - 8080:8080
      
volumes:
  db-data: {}
