version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app

  server:
    build: ./server
    volumes:
      - ./server:/usr/local/server
      - /usr/local/server/node_modules
    working_dir: /usr/local/server
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://root:password@db/app
      - JWT_SECRET=secret
    ports:
      - 3000:3000
    depends_on:
      - db

  app:
    build: ./app
    ports:
      - 8000:8000
    volumes:
      - ./app:/home/node
      - /home/node/node_modules

  adminer:
    image: adminer
    ports:
      - 8080:8080
      
volumes:
  db-data: {}